model_list:
  - model_name: deepseek-chat
    litellm_params:
      model: openai/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
      api_key: os.environ/DEEPSEEK_KEY
      api_base: https://api.siliconflow.cn/v1/
      # timeout: 10                      # timeout in (seconds)
      # stream_timeout: 10              # timeout for stream requests (seconds)
      # max_retries: 1

  - model_name: bedrock-claude-35
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_access_key_id: os.environ/GLOBAL_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/GLOBAL_AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/GLOBAL_AWS_REGION
      aws_bedrock_runtime_endpoint: os.environ/BEDROCK_RUNTIME_ENDPOINT
      extra_headers: {"key": "value"}
  #     timeout: 10                      # timeout in (seconds)
  #     stream_timeout: 10              # timeout for stream requests (seconds)
  #     max_retries: 1

  - model_name: bedrock-nova-v1
    litellm_params:
      model: bedrock/us.amazon.nova-lite-v1:0
      aws_access_key_id: os.environ/GLOBAL_AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/GLOBAL_AWS_SECRET_ACCESS_KEY
      aws_region_name: os.environ/GLOBAL_AWS_REGION
      # timeout: 10                      # timeout in (seconds)
      # stream_timeout: 10              # timeout for stream requests (seconds)
      # max_retries: 3

# general_settings:    
#     alerting: ["slack"]
general_settings: 
  database_url: os.environ/DATA_BASE_URL
  allow_requests_on_db_unavailable: true
  # background_health_checks: True # enable background health checks
  # health_check_interval: 300 # frequency of background health checks
  master_key: os.environ/MASTER_KEY

# router_settings:
#   fallbacks: [{"deepseek-chat": ["bedrock-nova-v1"]}]